CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "email" varchar DEFAULT '' NOT NULL, "encrypted_password" varchar DEFAULT '' NOT NULL, "reset_password_token" varchar, "reset_password_sent_at" datetime, "remember_created_at" datetime, "confirmation_token" varchar, "confirmed_at" datetime, "confirmation_sent_at" datetime, "unconfirmed_email" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "admin" boolean DEFAULT 'f');
INSERT INTO `users` VALUES (3,'iwenchak@gmail.com','$2a$11$3Yh.U4tA.AJdXe5QoWSwr.//HDooTLJOPWywjFgjdW1v4C.vwVxx6',NULL,NULL,NULL,'C9zykHxmFxxXtxvmxd2D','2017-05-06 07:13:19.394670','2017-05-06 07:13:02.407375',NULL,'2017-05-06 07:13:02.406875','2017-05-06 16:28:49.497374','t');
INSERT INTO `users` VALUES (4,'ukrainianbeehive@gmail.com','$2a$11$W8PFhMY1DbqEXm/iXeezVOADwmQJzatpdkvPKRaN6QXLZ6QkWsQ/O',NULL,NULL,NULL,'yzqb3Ttpytk4zyXjuYYA','2017-05-06 13:24:08.398703','2017-05-06 13:23:55.875864',NULL,'2017-05-06 13:23:55.875864','2017-05-07 06:22:31.758329','t');
INSERT INTO `users` VALUES (5,'yurad1ron@gmail.com','$2a$11$rVl8OUiqM9KyCvXqcgg1BOfXdIjuC2vhoomWM0Xy1bT.QPQykZWMy',NULL,NULL,NULL,'xh4-m6CGsFTPJSz7e9xy','2017-05-06 16:24:06.500064','2017-05-06 16:23:26.030359',NULL,'2017-05-06 16:23:26.030359','2017-05-06 16:24:06.502878','f');
INSERT INTO `users` VALUES (10,'ivantestersites@gmail.com','$2a$11$4Yhd.8Czvf7.CbKZuaQ9LOZ0giP0KV8z0iDStVoyUPHddOUru8c2C',NULL,NULL,NULL,'PVxT85_XDx5s_fc2S5hT','2017-05-06 20:41:29.023529','2017-05-06 20:41:24.683179',NULL,'2017-05-06 20:41:24.683179','2017-05-06 20:41:29.027117','f');
CREATE TABLE "specifications" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar, "text" text, "image" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
INSERT INTO `specifications` VALUES (1,'Ukrainian beehive Bjilnyk ','Brood chambers can be made either 8 or 10 standard Langstroth or Dadant frame different height, as well as supers by 17 or 21 of these frames or frame smaller height (medium, shallow or half-frame Dadant type). Thickness of wall board is 20 mm. You should pay attention to the size of the boxes (meter or inch standard and 8 or 10 frames).','specificationr.jpg','2017-05-13 20:22:32.825806','2017-05-14 07:15:55.165751');
CREATE TABLE "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY);
INSERT INTO `schema_migrations` VALUES ('20170424100804');
INSERT INTO `schema_migrations` VALUES ('20170425123505');
INSERT INTO `schema_migrations` VALUES ('20170427083053');
INSERT INTO `schema_migrations` VALUES ('20170428093032');
INSERT INTO `schema_migrations` VALUES ('20170501093350');
INSERT INTO `schema_migrations` VALUES ('20170504092030');
INSERT INTO `schema_migrations` VALUES ('20170506051821');
INSERT INTO `schema_migrations` VALUES ('20170506223358');
INSERT INTO `schema_migrations` VALUES ('20170511080303');
INSERT INTO `schema_migrations` VALUES ('20170511084609');
INSERT INTO `schema_migrations` VALUES ('20170511102721');
INSERT INTO `schema_migrations` VALUES ('20170513162656');
CREATE TABLE "products" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar, "text" text, "image" varchar, "image1" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
INSERT INTO `products` VALUES (8,'Ukrainian beehive Bjilnyk protect your bees.','Ukrainian beehive Bjilnyk is not just a new hive. This is not only a new technology. This is a new philosophy of beekeeping, which is based on deep understanding and full accounting of the laws of bees existence. This is a house for bee with optimal conditions existing throughout the year, which is a convenient and technological for beekeepers. Ukrainian beehive Bjilnyk is an invention that transforms the current state of relations between man and the honeybee to a new level.','photo_titul.JPG','Літо-огляд-нове.jpg','2017-04-25 06:07:21.195312','2017-05-10 14:58:15.921527');
INSERT INTO `products` VALUES (9,'- 1 -','During the cold period, Ukrainian Beehive Bjilnyk (UBB) provides unique protection of bees to a majority of threats and impacts. In winter and early spring, UBB gives for the bees nest a very good thermal conditions as above and on all sides are protected by two separate walls and a layer of air between them.','фото2.jpg','Фото3.JPG','2017-04-25 06:09:08.105874','2017-05-07 11:23:13.768235');
INSERT INTO `products` VALUES (11,'- 2 -','Internal bodies additionally wrapped by insulated cloth, which keeps warm air around bees as well as in the hollow of a tree with very thick walls.','Фото4.JPG','Фото5.JPG','2017-05-07 06:13:41.670457','2017-05-07 10:26:14.831151');
INSERT INTO `products` VALUES (12,'- 3 -','As seen in infrared images, unlike conventional hives, in UBB virtually no heat loss is happening through the notch, vertical ventilation, as well as through thin walls. The bees consume significantly less food and are not worn out. And in early spring with a significant reduction of temperature there is no danger of hypothermia and brood disease.','Фото6.jpg','Фото7.jpg','2017-05-07 11:30:31.010586','2017-05-07 11:33:15.324934');
INSERT INTO `products` VALUES (13,'- 4 -','As insulated cloth it is best to use the material with a reflective surface of a thin layer of aluminum foil. This cover reduces heat losses not only by convection (air flow), but also by thermal emission (infrared waves). Also, such continuous cover of aluminum foil protects bee nest from fluctuations of the magnetic field. Some beekeepers offer to ground this protective shell by the thin copper wire.','Фото8.JPG','Фото9.JPG','2017-05-07 11:35:06.065237','2017-05-07 11:35:06.065237');
INSERT INTO `products` VALUES (14,'- 5 -','Bee nest in UBB is protected from the noise and stress much better than in other hives because the winter cluster is located behind two separate walls, between which there is no binding element. Therefore, wind, rain, hail, anthropogenic noise or birds (woodpeckers, titmice, etc.) do not violate the peace of bees. They eat much less food and are less worn out during the winter, because each disturbance leads to the loss of additional energy and vitality. Vibration from transport or domestic machinery or even walking near by the hive can disturb the bee cluster. But in UBB inner chambers in winter are set on two thin laths, which rest on the bottom only by their ends. Due to this, much of the vibration is absorbed.Also, it improves ventilation and moisture removal from the bottom of the nest.','Фото10.JPG','фото11.JPG','2017-05-07 11:37:29.767353','2017-05-07 11:37:29.767353');
INSERT INTO `products` VALUES (15,'- 6 -','The bottom panel of UBB is composed of individual boards, some of them are not fixed. These, nonfixed segments of the bottom are very easy to pull out or insert from the sides of UBB regulating the size of the opening. This opening from the top or the bottom could be covered with shallow ventilation mesh or queen excluder. This allows adjustable ventilation in the winter or in summer migrations, protection from mice and birds, separation from fallen Varroa mites and waste or limitation of the bees from flying when pesticides are used in surrounding areas. ','Фото12.JPG','Фото13.jpg','2017-05-07 11:39:09.317999','2017-05-07 11:39:09.317999');
INSERT INTO `products` VALUES (16,'- 7 -','In the winter to protect from excessive moisture, Ukrainian beehive Bjilnyk is equipped with a unique ventilation system with heat recovery. This system removes the moisture produced by the consumption of honey by bees, and the heat of vent gasses and heat that generated by steam condensation is kept under insulation cloth around bee nest. The intensity of such ventilation in winter depends on the outside temperature and increases by warming and decreases when the temperature drops. For example, in warm days it is more intensive than in cold nights. Such feature helps saving energy and heat (food stored) accordingly. Instead, in the traditional system of ventilation through the opening in the inner cover by falling outdoor temperature the ventilation flow increases and bees have to spend way more food and energy for heating of the nest and the atmosphere.
For optimum setting and adjustment of such ventilation system with heat recovery beekeeper should take into account the climatic conditions and the size of bee colony. By proper selection of the diameter of vent tube and height of its outer end, and by regulating the working section of ventilation ducts depending on the weather it is possible to maintain optimal conditions in the bees nest. 
All these technical features of Ukrainian beehive Bjilnyk enable the bee''s cluster to be in deep tranquility all winter long and depending on climatic conditions and size of the colony to spend 2-2.5 times less honey than traditionally. Reduced load on the intestine minimizes the threat of Nozema and other infectious diseases.
Wintering and intensity of spring development are very dependent on the size of the colony and the state of its individuals. In autumn you can increase the size of the colony by feeding sugar syrup, but this usually impairs the "quality" of bees. Therefore, the best way to get a large colony is combining several smaller ones. With the first autumn frosts the bottom of UBB is overturned, and one chamber is installed on the top of the other of two chambers of adjacent bee colonies. Thus forming well prepared for wintering a large bee colony. In this case the bees do not conflict, form a common cluster and, usually in the spring, bees remove the weaker queen.
With this merger you can accommodate food stocks so that bee cluster and brood in spring were in the warmest area under the cover of the upper body. 
The honey and beebread frames are placed in the lower chamber for spring development. 
Thanks to the comfortable conditions, the bee colony in UBB during the winter is in a state of deep tranquility and the queen starts laying eggs later, usually after first flight. This reduces consumption of honey and preserves "vitality" of the winter bees. Also, this will significantly reduce the likelihood of hypothermia of brood and its infection (foulbrood, fungal diseases).
Very often in the traditional hive during winter warming the spring sun warms the thin front wall and provokes the emergence of the early brood. Heating of the brood requires a lot of energy, and if cold returns, the family may die from the lack of food or diarrhea.
In UBB, the insulated cloth creates the thermal cover around the nest, so the bee colony is developing very quickly and in the presence of food within six weeks after the first flight occupies both chambers. Good thermal conditions of UBB also contribute to better collection of spring nectar and pollen as more bees can switch from heating to the field work.
','Фото14.JPG','Фото15.JPG','2017-05-07 11:41:32.573161','2017-05-07 11:41:32.573161');
INSERT INTO `products` VALUES (17,'- 8 -','Maintaining the high intensity of growth and preventing swarming, the nest could be expanded, used for packages or splits. If you need to split the colony, the bottom is overturned and two new small boxes with wax foundations are set next to each other. Above each of them are placed chambers with bees. In queenless colonies new queen or queen cells are added. After the lower boxes with foundations are build up, they are placed on the top. To collect nectar above them, queen excluders are placed on them and large expanded super is installed above.
With the gradual development and occupation of this box, one colony with two queens is peacefully formed and adjusted of different sizes of colonies. The productivity of such united colony far exceeds the overall performance of two separate colonies!!!         
Honey supers are placed one top as bee colony develops further.','Фото16.jpg','Фото17.JPG','2017-05-07 11:53:25.226565','2017-05-07 11:53:25.226565');
INSERT INTO `products` VALUES (18,'- 9 -','UBB allows an easy access to the brood chambers without removing the heavy honey supers. A beekeeper can easily lift common honey suppers with no help and set the thin bar or plank under. After fixing one of the sides of the honey supers by stretching or extra weight, the brood chambers on the opposite side can be easily removed and returned to the place. Thus beekeeper can check brood chambers, change their location, cut the drone brood or medicate brood area without full dismantling of the hive.','Фото18.jpg','Фото19.jpg','2017-05-07 11:56:27.535653','2017-05-07 11:56:27.535653');
INSERT INTO `products` VALUES (19,'- 10 -','As one of the methods of removal of the bees for honey harvesting, the thin film is placed under honey super and their entrance openings are prolonged by tubes. The film can also be used to split the hive and for creating temporary antiswarming  nuc or future colonies. Beekeeper doesn''t have to lift or carry heavy boxes. Also, this allows to avoid creation of defective nuc colonies without flying bees. By combining temporary anti-swarm nucs or a pair of big colonies, bees select the best queen themselves, i.e. the replacement of the queens taking place every year without significant problems.

Overall UBB makes it possible to use almost all modern beekeeping techniques and virtually all available type of standard equipment. Smaller boxes can be made either on 8 or 10 standard frames and big honey supers accordingly 17 or 21 the same or lower height frames. Bjilnyk is more stable both in backyard beekeeping and for migrations, and in its production requires less wood than for typical hives.

Ukrainian Beehive Bjilnyk is a very convenient for beekeepers and is an ideal shelter for bees throughout the annual cycle. It promotes and supports the sustainable immunity of the bee colonies and increases their survival in today''s difficult conditions.','Фото20.JPG','Фото21.JPG','2017-05-07 11:58:16.782354','2017-05-07 12:22:06.958767');
CREATE TABLE "galleries" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar, "image" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
INSERT INTO `galleries` VALUES (5,'He is wizard','DSC_0160.JPG','2017-04-27 09:31:11.192029','2017-04-27 09:31:11.192029');
INSERT INTO `galleries` VALUES (6,'Iurii Dron and his inventions','DSC_0182.JPG','2017-04-27 10:15:54.249399','2017-05-14 09:48:06.179726');
INSERT INTO `galleries` VALUES (7,'UBB with 3 brood chambers (each has 10 deep Dadant frames (hight 30 cm)) and 3 level of honey supers with the same frames (totaly 122 deep Dadant type frames)','DSC_0140.JPG','2017-04-27 10:29:11.159308','2017-05-14 09:48:20.397959');
INSERT INTO `galleries` VALUES (9,'UBB with 4 brood chambers (each has 8 deep Langstroth frames) and 2 honey supers with 17 the same frames (totaly 66 deep Langstroth frames)','DSC_0141.JPG','2017-04-27 10:30:46.970519','2017-05-14 10:06:45.301850');
INSERT INTO `galleries` VALUES (10,'UBB in summer','DSCN2096.JPG','2017-04-27 10:32:34.409833','2017-05-14 09:17:37.479140');
INSERT INTO `galleries` VALUES (15,'UBB in winter','DSCN2176.JPG','2017-05-12 18:49:22.396152','2017-05-14 09:20:50.161285');
INSERT INTO `galleries` VALUES (16,'In winter, UBB inside','фото2.jpg','2017-05-12 18:50:18.042044','2017-05-14 09:26:16.850265');
INSERT INTO `galleries` VALUES (17,'Bee nest is installed on two thin slats for good ventilation, moisture remove and noise protections','DSCN2186.JPG','2017-05-12 18:56:18.189346','2017-05-14 09:47:35.563247');
INSERT INTO `galleries` VALUES (18,'Insulation cloth with reflective surface for keep heat and protection from fluctuations of the magnetic field','DSCN2211.JPG','2017-05-12 18:57:27.911323','2017-05-14 09:49:01.926346');
INSERT INTO `galleries` VALUES (19,'The bottom with regulating opening for vent','DSCN2208.JPG','2017-05-12 18:59:45.516433','2017-05-14 09:42:22.269306');
INSERT INTO `galleries` VALUES (20,'Scheme for installing a protective mesh above the adjustable bottom opening','Фото13.jpg','2017-05-12 19:00:50.715628','2017-05-14 09:46:58.010909');
INSERT INTO `galleries` VALUES (21,'Unique  ventilation system with heat recovery','Фото14.JPG','2017-05-12 19:01:52.938210','2017-05-14 09:52:58.163995');
INSERT INTO `galleries` VALUES (22,'Infrared image of UBB in winter','Фото6.jpg','2017-05-12 19:03:29.355362','2017-05-14 09:54:47.497434');
INSERT INTO `galleries` VALUES (23,'Scheme of extraction of the brood chamber','Літо-огляд-нове.jpg','2017-05-12 19:05:17.376903','2017-05-14 09:57:12.881975');
INSERT INTO `galleries` VALUES (24,'The lifting common supers and setting the thin bar','Фото18.jpg','2017-05-12 19:05:39.320347','2017-05-14 10:01:41.612161');
INSERT INTO `galleries` VALUES (25,'The removing a brood chambers','Фото19.jpg','2017-05-12 19:06:16.650018','2017-05-14 10:03:20.627357');
CREATE TABLE "films" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar, "text" text, "video" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
INSERT INTO `films` VALUES (24,'Ukrainian beehive Bjilnyk promo video','','UBB_promo.mp4','2017-05-09 11:27:01.140047','2017-05-10 14:37:13.563210');
CREATE TABLE "comments" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`commenter`	varchar,
	`body`	text,
	`article_id`	integer,
	`created_at`	datetime NOT NULL,
	`updated_at`	datetime NOT NULL,
	`email`	TEXT
);
INSERT INTO `comments` VALUES (25,'Iurii','UBB eliminates or minimizes the negative impact of factors that deplete the immune system of bees and cause of death, especially in the most difficult winter period. Excellent protection against cold, noise, vibrations, oscillations of the magnetic field, excessive moisture, pests, birds, extreme outdoor temperature, sunlight and wind provide bees opportunity to be in deep dormancy (hibernation, calm) throughout the winter, while consuming a minimum amount of food. UBB also creates optimal conditions for spring development of bee colonies and prevents the brood from hypothermia and helps  defeating infectious diseases. Thus UBB contributes to survival bee colony even in those circumstances, where traditional methods do not work.',2,'2017-05-14 07:42:27.979429','2017-05-14 07:42:28.133026','ukrainianbeehive@gmail.com');
INSERT INTO `comments` VALUES (26,'Iurii','UBB is designed for maximum satisfaction of the needs of bees. But at the same time it is very convenient and technological for the beekeeper. In UBB used standard Langstroth frame and maintenance do not need any special equipment.
The main disadvantage of UBB is that large honey supers are twice as  heavy as conventional hives. Such supers could be removed and carried by two people. With a small number of hives honey harvesting could be done by taking frames separately. 
Also, UBB can not guarantee the safety against bee poisoning, poor diet or infectious diseases and parasites.',3,'2017-05-14 07:44:01.950240','2017-05-14 07:44:02.125715','ukrainianbeehive@gmail.com');
INSERT INTO `comments` VALUES (27,'Iurii','By keeping bees in UBB, virtually all known methods could be used to combat the varroa mite. Through improved access to the brood chambers, the procedure of cutting out drone brood from the frame and installation of medications directly into the bee nest is greatly simplified.
Availability of bottom with mesh opening, what easily can be opened (closed), makes it possible to significantly increase the effectiveness of anti-mite medications, especially when using substances that evaporate easily.',11,'2017-05-14 07:48:09.142812','2017-05-14 07:48:09.329897','ukrainianbeehive@gmail.com');
CREATE TABLE "beekeepers" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "text" text, "title" varchar, "url1" text, "url2" text, "url3" text, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "image" varchar, "image1" varchar);
INSERT INTO `beekeepers` VALUES (12,'Ukrainian beehive Bjilnyk - is not just a new hive. This is not only a new technology. This is a new philosophy of beekeeping, which is based on deep understanding and full accounting of the laws of  bees existence. This is a house for bee with optimal conditions existing throughout the year, which is a convenient and technological for beekeepers both in stationary apiary and in migrations. Ukrainian beehive Bjilnyk - an invention that transforms the current state of relations between man and the honeybee to a new level. Follow UBB in social media','Ukrainian beehive Bjilnyk','https://www.facebook.com/ukrbeehive','https://twitter.com/IuriiDron','https://www.instagram.com/ukrainianbeehive','2017-05-12 19:40:39.526304','2017-05-14 08:10:44.759001','photo_titul.JPG','DSCN2176.JPG');
INSERT INTO `beekeepers` VALUES (13,'Iurii Dron, scientist from Ukraine, pHD in Biology who started beekeeping 20 years ago. Although his grandfather was a beekeeper and had many hives, he had to start from scratch. Working in Chernivtsi National University, Ukraine, he’d researched soils. Beekeeping was only his hobby and pleasure of the weekends.
Gradually, step by step, he increasingly immersed in the wonderful world of beekeeping, revealing more and more of its aspects. In 2009, based on 5-year experiments with bees and their housing, he decided to patent invented by him beehive. Work on improving its research really captured him and the results embodied today in a very practical and useful Ukrainian beehive Bjilnyk (UBB). 
Overall in beekeeping today, he possesses 5 patents in Ukraine and abroad, several scientific articles, the textbook. He is a member of COLOSS association and NGO "Bukovynian beekeeper." Currently he maintains about 5-7 bee colonies and he still is a hobby beekeeper.','Iurii Dron ','https://www.facebook.com/iurii.dron.7','https://www.linkedin.com/in/iurii-dron-266b1034','','2017-05-12 19:46:43.214171','2017-05-12 19:46:43.214171','DSC_0161.JPG',NULL);
INSERT INTO `beekeepers` VALUES (14,'Vadim Manzhos is a seasoned beekeeper with 30 years of experience in two countries - Ukraine and USA (Southern California and Montana) specializing in record high honey production from single hive working with many different types of hives and beekeeping technics including multiple queens in single hives.','Vadim Manzhos','https://www.facebook.com/vadim.manzhos?fref=ts','https://www.linkedin.com/in/vadim-manzhos-3230ba28','','2017-05-12 19:59:12.308258','2017-05-14 06:49:38.464920','Manjos.jpg',NULL);
CREATE TABLE "articles" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "text" text, "email" varchar, "author" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
INSERT INTO `articles` VALUES (2,'  Why UBB promotes the survival of bees?','NUWER@gmail.com',' Iurii ','2017-04-29 13:14:32.202675','2017-05-14 07:36:34.801922');
INSERT INTO `articles` VALUES (3,'What are the disadvantages of UBB?','STEPHYIN@yahoo.com',' Iurii ','2017-04-29 13:16:15.318591','2017-05-14 07:38:09.114407');
INSERT INTO `articles` VALUES (11,'How to deal with varroa mites in UBB?','ivantestersites@gmail.com',' Iurii ','2017-05-07 06:10:32.568881','2017-05-14 07:40:01.010569');
CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
INSERT INTO `ar_internal_metadata` VALUES ('environment','development','2017-04-24 10:12:37.935960','2017-04-24 10:12:37.935960');
CREATE UNIQUE INDEX "index_users_on_reset_password_token" ON "users" ("reset_password_token");
CREATE UNIQUE INDEX "index_users_on_email" ON "users" ("email");
CREATE UNIQUE INDEX "index_users_on_confirmation_token" ON "users" ("confirmation_token");
CREATE INDEX "index_comments_on_article_id" ON "comments" ("article_id")
;
COMMIT;
